Repository apple/swift-openapi-urlsession, pull requests merged in 2025-04, with the labels that each got.

#72 Enable macOS CI on pull requests
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#68 Add support for opting out of streaming HTTP bodies
  Sources/OpenAPIURLSession/URLSessionTransport.swift
Labels: 🆕 semver/minor, kind/feature

#71 Add support for Windows
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Package.swift
  README.md
  Sources/OpenAPIURLSession/BufferedStream/Lock.swift
  Tests/OpenAPIURLSessionTests/NIOAsyncHTTP1TestServer.swift
  Tests/OpenAPIURLSessionTests/TaskCancellationTests.swift
  Tests/OpenAPIURLSessionTests/URLSessionTransportTests.swift
Labels: 🔨 semver/patch

#73 Enable Swift 6.1 jobs in CI
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none
